const CustomerActionTypes = {
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  RETRIEVE_CUSTOMERS: 'RETRIEVE_CUSTOMERS',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  DELETE_CUSTOMER: 'DELETE_CUSTOMER',
  DELETE_ALL_CUSTOMERS: 'DELETE_ALL_CUSTOMERS',
};

export default CustomerActionTypes;
